---

- hosts: local
  connection: local
  gather_facts: false
  tasks:
    - name: Add bootstrap host to dynamic inventory
      add_host: name={{ CLIENT_IP }} serveraddr={{ CLIENT_IP }} ansible_ssh_port={{ SSH_PORT }} servername={{ CLIENT_HOSTNAME }} groupname={{ HOST_GROUP }}

- hosts: "{{ HOST_GROUP }}"
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: keys/ansible.key
    http_proxy: "{{ proxy.http }}"
    https_proxy: "{{ proxy.https }}"
  roles:
    - { role: arda-client, method: 'checkin' } 
